export const PRODUCT_SELECTED_SUCCESS = 'PRODUCT_SELECTED_SUCCESS';
export const CONFIRM_PRODUCT_SUCCESS = 'CONFIRM_PRODUCT_SUCCESS';
export const DELETED_SUCCESS = 'DELETED_SUCCESS';
export const TOTAL_SUCCESS = 'TOTAL_SUCCESS';
export const SUBTOTAL_SUCCESS = 'SUBTOTAL_SUCCESS';
export const MY_ORDEN = 'MY_ORDEN';
